id: 5c5c9a24eac1437db64bd049002cb667
initial_creation_type: ocr
created_at: 26/09/2021
last_modified_at: 2021-12-20 10:25:28.937448
source_metadata:
  id: bdr:W21848
  title: བུ་སྟོན་གྱི་སྐར་རྩིས་ཕྱོགས་བསྒྲིགས།
  volumes:
    8e09c89221924b8d87e9b61f037058d9:
      image_group_id: I1KG12340
      title: ''
      base_file: v001.txt
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
